### ISSUE TITLE
pushed to AWS: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by grandmore** [convox-examples/node-workers#1]
I used this app as an example of a working node app so I can diagnose a different issue. However it has errors when deployed to convox on aws.

Dead process 36ac82aa9a7b 
Starting process 209d31765d7c 
Dead process 209d31765d7c 
events.js:141 
       throw er; // Unhandled 'error' event 
convox-node/worker:RSKVGROWRTC :       ^ 
  
Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379 
     at errnoException (dns.js:26:10) 
     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

**Comment by mattmanning** [comment]
@grandmore Thanks for reporting. The links have been fixed and this is working now. Please let us know if you have more problems with it.
